// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using printer.Data;

#nullable disable

namespace printer.Migrations
{
    [DbContext(typeof(PrinterDbContext))]
    [Migration("20260323193417_AddPrinterMaintainer")]
    partial class AddPrinterMaintainer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("printer.Data.Entities.AlertRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Code")
                        .HasColumnType("int")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Message")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("message");

                    b.Property<int>("PrinterId")
                        .HasColumnType("int")
                        .HasColumnName("printer_id");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("resolved_at");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("state");

                    b.HasKey("Id");

                    b.HasIndex("State");

                    b.HasIndex("PrinterId", "State");

                    b.ToTable("alert_records");
                });

            modelBuilder.Entity("printer.Data.Entities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_login_at");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("note");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("phone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Role");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("app_users");
                });

            modelBuilder.Entity("printer.Data.Entities.BillingTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<decimal>("DiscountPercentBlack")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("discount_percent_black");

                    b.Property<decimal>("DiscountPercentColor")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("discount_percent_color");

                    b.Property<decimal>("DiscountPercentLarge")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("discount_percent_large");

                    b.Property<int>("FreeBlackPages")
                        .HasColumnType("int")
                        .HasColumnName("free_black_pages");

                    b.Property<int>("FreeColorPages")
                        .HasColumnType("int")
                        .HasColumnName("free_color_pages");

                    b.Property<int>("FreeLargePages")
                        .HasColumnType("int")
                        .HasColumnName("free_large_pages");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<decimal>("MonthlyFee")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("monthly_fee");

                    b.Property<int>("MonthlyFeeCycle")
                        .HasColumnType("int")
                        .HasColumnName("monthly_fee_cycle");

                    b.Property<DateOnly?>("MonthlyStartDate")
                        .HasColumnType("date")
                        .HasColumnName("monthly_start_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<int>("PageFeeCycle")
                        .HasColumnType("int")
                        .HasColumnName("page_fee_cycle");

                    b.Property<int>("PageMethod")
                        .HasColumnType("int")
                        .HasColumnName("page_method");

                    b.Property<DateOnly?>("PageStartDate")
                        .HasColumnType("date")
                        .HasColumnName("page_start_date");

                    b.Property<decimal>("PricePerBlack")
                        .HasPrecision(10, 4)
                        .HasColumnType("decimal(10,4)")
                        .HasColumnName("price_per_black");

                    b.Property<decimal>("PricePerColor")
                        .HasPrecision(10, 4)
                        .HasColumnType("decimal(10,4)")
                        .HasColumnName("price_per_color");

                    b.Property<decimal>("PricePerLarge")
                        .HasPrecision(10, 4)
                        .HasColumnType("decimal(10,4)")
                        .HasColumnName("price_per_large");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Name");

                    b.ToTable("billing_templates");
                });

            modelBuilder.Entity("printer.Data.Entities.BillingTier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BillingConfigId")
                        .HasColumnType("int")
                        .HasColumnName("billing_config_id");

                    b.Property<int?>("BillingTemplateId")
                        .HasColumnType("int")
                        .HasColumnName("billing_template_id");

                    b.Property<int>("FromPages")
                        .HasColumnType("int")
                        .HasColumnName("from_pages");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 4)
                        .HasColumnType("decimal(10,4)")
                        .HasColumnName("price");

                    b.Property<int>("TierOrder")
                        .HasColumnType("int")
                        .HasColumnName("tier_order");

                    b.Property<int>("TierType")
                        .HasColumnType("int")
                        .HasColumnName("tier_type");

                    b.Property<int?>("ToPages")
                        .HasColumnType("int")
                        .HasColumnName("to_pages");

                    b.HasKey("Id");

                    b.HasIndex("BillingConfigId", "TierType", "TierOrder");

                    b.HasIndex("BillingTemplateId", "TierType", "TierOrder");

                    b.ToTable("billing_tiers");
                });

            modelBuilder.Entity("printer.Data.Entities.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("image_path");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("brands");
                });

            modelBuilder.Entity("printer.Data.Entities.ClientStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Ip")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ip");

                    b.Property<DateTime>("LastReport")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_report");

                    b.Property<string>("MachineId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("machine_id");

                    b.Property<string>("OsInfo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("os_info");

                    b.Property<int?>("PartnerId")
                        .HasColumnType("int")
                        .HasColumnName("partner_id");

                    b.Property<int>("PrinterCount")
                        .HasColumnType("int")
                        .HasColumnName("printer_count");

                    b.Property<string>("Version")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("LastReport");

                    b.HasIndex("MachineId")
                        .IsUnique();

                    b.HasIndex("PartnerId");

                    b.ToTable("client_status");
                });

            modelBuilder.Entity("printer.Data.Entities.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BillingPeriod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("billing_period");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("confirmed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<decimal>("GrandTotal")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("grand_total");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("invoice_number");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("note");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("paid_at");

                    b.Property<int>("PartnerId")
                        .HasColumnType("int")
                        .HasColumnName("partner_id");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("date")
                        .HasColumnName("period_end");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("date")
                        .HasColumnName("period_start");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<decimal>("TaxAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("tax_amount");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("total_amount");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceNumber")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("PartnerId", "BillingPeriod");

                    b.ToTable("invoices");
                });

            modelBuilder.Entity("printer.Data.Entities.InvoiceItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BillingType")
                        .HasColumnType("int")
                        .HasColumnName("billing_type");

                    b.Property<int>("BlackPages")
                        .HasColumnType("int")
                        .HasColumnName("black_pages");

                    b.Property<int>("ColorPages")
                        .HasColumnType("int")
                        .HasColumnName("color_pages");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("description");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("int")
                        .HasColumnName("invoice_id");

                    b.Property<int>("LargePages")
                        .HasColumnType("int")
                        .HasColumnName("large_pages");

                    b.Property<decimal>("MonthlyFee")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("monthly_fee");

                    b.Property<decimal>("PageFee")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("page_fee");

                    b.Property<int>("PrinterId")
                        .HasColumnType("int")
                        .HasColumnName("printer_id");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("subtotal");

                    b.HasKey("Id");

                    b.HasIndex("PrinterId");

                    b.HasIndex("InvoiceId", "PrinterId");

                    b.ToTable("invoice_items");
                });

            modelBuilder.Entity("printer.Data.Entities.Partner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("address");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("code");

                    b.Property<string>("ContactName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("contact_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("email");

                    b.Property<string>("Fax")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("fax");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsCompany")
                        .HasColumnType("bit")
                        .HasColumnName("is_company");

                    b.Property<string>("Mobile")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("mobile");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("note");

                    b.Property<string>("PartnerNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("partner_number");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("phone");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("state");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("Vat")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("vat");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.HasIndex("State");

                    b.ToTable("partners");
                });

            modelBuilder.Entity("printer.Data.Entities.PartnerBillingInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("email");

                    b.Property<int>("PartnerId")
                        .HasColumnType("int")
                        .HasColumnName("partner_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("PartnerId");

                    b.ToTable("partner_billing_infos");
                });

            modelBuilder.Entity("printer.Data.Entities.PartnerContact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("email");

                    b.Property<string>("Mobile")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("mobile");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<int>("PartnerId")
                        .HasColumnType("int")
                        .HasColumnName("partner_id");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("phone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("PartnerId");

                    b.ToTable("partner_contacts");
                });

            modelBuilder.Entity("printer.Data.Entities.PartnerModule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EnabledAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("enabled_at");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit")
                        .HasColumnName("is_enabled");

                    b.Property<int>("ModuleId")
                        .HasColumnType("int")
                        .HasColumnName("module_id");

                    b.Property<int>("PartnerId")
                        .HasColumnType("int")
                        .HasColumnName("partner_id");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.HasIndex("PartnerId", "ModuleId")
                        .IsUnique();

                    b.ToTable("partner_modules");
                });

            modelBuilder.Entity("printer.Data.Entities.PrintRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BlackSheets")
                        .HasColumnType("int")
                        .HasColumnName("black_sheets");

                    b.Property<int>("ColorSheets")
                        .HasColumnType("int")
                        .HasColumnName("color_sheets");

                    b.Property<int>("Count")
                        .HasColumnType("int")
                        .HasColumnName("count");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<int>("LargeSheets")
                        .HasColumnType("int")
                        .HasColumnName("large_sheets");

                    b.Property<int?>("PartnerId")
                        .HasColumnType("int")
                        .HasColumnName("partner_id");

                    b.Property<int>("PrinterId")
                        .HasColumnType("int")
                        .HasColumnName("printer_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("state");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("PartnerId");

                    b.HasIndex("PrinterId", "Date", "State");

                    b.ToTable("print_records");
                });

            modelBuilder.Entity("printer.Data.Entities.Printer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("code");

                    b.Property<int>("ContractAlertDays")
                        .HasColumnType("int")
                        .HasColumnName("contract_alert_days");

                    b.Property<DateOnly?>("ContractEndDate")
                        .HasColumnType("date")
                        .HasColumnName("contract_end_date");

                    b.Property<DateOnly?>("ContractStartDate")
                        .HasColumnType("date")
                        .HasColumnName("contract_start_date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("Deposit")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("deposit");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<float?>("DrumBlack")
                        .HasColumnType("real")
                        .HasColumnName("drum_black");

                    b.Property<int>("DrumBlackAlertThreshold")
                        .HasColumnType("int")
                        .HasColumnName("drum_black_alert_threshold");

                    b.Property<float?>("DrumCyan")
                        .HasColumnType("real")
                        .HasColumnName("drum_cyan");

                    b.Property<int>("DrumCyanAlertThreshold")
                        .HasColumnType("int")
                        .HasColumnName("drum_cyan_alert_threshold");

                    b.Property<float?>("DrumMagenta")
                        .HasColumnType("real")
                        .HasColumnName("drum_magenta");

                    b.Property<int>("DrumMagentaAlertThreshold")
                        .HasColumnType("int")
                        .HasColumnName("drum_magenta_alert_threshold");

                    b.Property<float?>("DrumYellow")
                        .HasColumnType("real")
                        .HasColumnName("drum_yellow");

                    b.Property<int>("DrumYellowAlertThreshold")
                        .HasColumnType("int")
                        .HasColumnName("drum_yellow_alert_threshold");

                    b.Property<string>("Ip")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ip");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("Mac")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("mac");

                    b.Property<int?>("ModelId")
                        .HasColumnType("int")
                        .HasColumnName("model_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.Property<int?>("PartnerId")
                        .HasColumnType("int")
                        .HasColumnName("partner_id");

                    b.Property<string>("PartnerNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("partner_number");

                    b.Property<string>("PrinterName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("printer_name");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("serial_number");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("state");

                    b.Property<float?>("TonerBlack")
                        .HasColumnType("real")
                        .HasColumnName("toner_black");

                    b.Property<int>("TonerBlackAlertThreshold")
                        .HasColumnType("int")
                        .HasColumnName("toner_black_alert_threshold");

                    b.Property<float?>("TonerCyan")
                        .HasColumnType("real")
                        .HasColumnName("toner_cyan");

                    b.Property<int>("TonerCyanAlertThreshold")
                        .HasColumnType("int")
                        .HasColumnName("toner_cyan_alert_threshold");

                    b.Property<float?>("TonerMagenta")
                        .HasColumnType("real")
                        .HasColumnName("toner_magenta");

                    b.Property<int>("TonerMagentaAlertThreshold")
                        .HasColumnType("int")
                        .HasColumnName("toner_magenta_alert_threshold");

                    b.Property<float?>("TonerWaste")
                        .HasColumnType("real")
                        .HasColumnName("toner_waste");

                    b.Property<float?>("TonerYellow")
                        .HasColumnType("real")
                        .HasColumnName("toner_yellow");

                    b.Property<int>("TonerYellowAlertThreshold")
                        .HasColumnType("int")
                        .HasColumnName("toner_yellow_alert_threshold");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ContractEndDate");

                    b.HasIndex("ModelId");

                    b.HasIndex("PartnerId");

                    b.HasIndex("SerialNumber");

                    b.HasIndex("State");

                    b.ToTable("printers");
                });

            modelBuilder.Entity("printer.Data.Entities.PrinterBillingConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<decimal>("DiscountPercentBlack")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("discount_percent_black");

                    b.Property<decimal>("DiscountPercentColor")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("discount_percent_color");

                    b.Property<decimal>("DiscountPercentLarge")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("discount_percent_large");

                    b.Property<int>("FreeBlackPages")
                        .HasColumnType("int")
                        .HasColumnName("free_black_pages");

                    b.Property<int>("FreeColorPages")
                        .HasColumnType("int")
                        .HasColumnName("free_color_pages");

                    b.Property<int>("FreeLargePages")
                        .HasColumnType("int")
                        .HasColumnName("free_large_pages");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit")
                        .HasColumnName("is_enabled");

                    b.Property<DateOnly?>("LastMonthlyBilledDate")
                        .HasColumnType("date")
                        .HasColumnName("last_monthly_billed_date");

                    b.Property<DateOnly?>("LastPageBilledDate")
                        .HasColumnType("date")
                        .HasColumnName("last_page_billed_date");

                    b.Property<decimal>("MonthlyFee")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("monthly_fee");

                    b.Property<int>("MonthlyFeeCycle")
                        .HasColumnType("int")
                        .HasColumnName("monthly_fee_cycle");

                    b.Property<DateOnly?>("MonthlyStartDate")
                        .HasColumnType("date")
                        .HasColumnName("monthly_start_date");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("note");

                    b.Property<int>("PageFeeCycle")
                        .HasColumnType("int")
                        .HasColumnName("page_fee_cycle");

                    b.Property<int>("PageMethod")
                        .HasColumnType("int")
                        .HasColumnName("page_method");

                    b.Property<DateOnly?>("PageStartDate")
                        .HasColumnType("date")
                        .HasColumnName("page_start_date");

                    b.Property<decimal>("PricePerBlack")
                        .HasPrecision(10, 4)
                        .HasColumnType("decimal(10,4)")
                        .HasColumnName("price_per_black");

                    b.Property<decimal>("PricePerColor")
                        .HasPrecision(10, 4)
                        .HasColumnType("decimal(10,4)")
                        .HasColumnName("price_per_color");

                    b.Property<decimal>("PricePerLarge")
                        .HasPrecision(10, 4)
                        .HasColumnType("decimal(10,4)")
                        .HasColumnName("price_per_large");

                    b.Property<int>("PrinterId")
                        .HasColumnType("int")
                        .HasColumnName("printer_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("PrinterId")
                        .IsUnique();

                    b.ToTable("printer_billing_configs");
                });

            modelBuilder.Entity("printer.Data.Entities.PrinterMaintainer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("PrinterId")
                        .HasColumnType("int")
                        .HasColumnName("printer_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("role");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("PrinterId", "UserId")
                        .IsUnique();

                    b.ToTable("printer_maintainers");
                });

            modelBuilder.Entity("printer.Data.Entities.PrinterModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int")
                        .HasColumnName("brand_id");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("Feature")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("feature");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("image_path");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("state");

                    b.Property<bool>("Verify")
                        .HasColumnType("bit")
                        .HasColumnName("verify");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("[code] IS NOT NULL");

                    b.HasIndex("Name");

                    b.HasIndex("State");

                    b.ToTable("printer_models");
                });

            modelBuilder.Entity("printer.Data.Entities.SystemModule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("icon");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit")
                        .HasColumnName("is_enabled");

                    b.Property<string>("MenuAction")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("menu_action");

                    b.Property<string>("MenuController")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("menu_controller");

                    b.Property<string>("MenuPath")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("menu_path");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("SortOrder");

                    b.ToTable("system_modules");
                });

            modelBuilder.Entity("printer.Data.Entities.AlertRecord", b =>
                {
                    b.HasOne("printer.Data.Entities.Printer", "Printer")
                        .WithMany("AlertRecords")
                        .HasForeignKey("PrinterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Printer");
                });

            modelBuilder.Entity("printer.Data.Entities.BillingTier", b =>
                {
                    b.HasOne("printer.Data.Entities.PrinterBillingConfig", "BillingConfig")
                        .WithMany("Tiers")
                        .HasForeignKey("BillingConfigId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("printer.Data.Entities.BillingTemplate", "BillingTemplate")
                        .WithMany("Tiers")
                        .HasForeignKey("BillingTemplateId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("BillingConfig");

                    b.Navigation("BillingTemplate");
                });

            modelBuilder.Entity("printer.Data.Entities.ClientStatus", b =>
                {
                    b.HasOne("printer.Data.Entities.Partner", "Partner")
                        .WithMany()
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("printer.Data.Entities.Invoice", b =>
                {
                    b.HasOne("printer.Data.Entities.Partner", "Partner")
                        .WithMany()
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("printer.Data.Entities.InvoiceItem", b =>
                {
                    b.HasOne("printer.Data.Entities.Invoice", "Invoice")
                        .WithMany("Items")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("printer.Data.Entities.Printer", "Printer")
                        .WithMany()
                        .HasForeignKey("PrinterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Invoice");

                    b.Navigation("Printer");
                });

            modelBuilder.Entity("printer.Data.Entities.PartnerBillingInfo", b =>
                {
                    b.HasOne("printer.Data.Entities.Partner", "Partner")
                        .WithMany("BillingInfos")
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("printer.Data.Entities.PartnerContact", b =>
                {
                    b.HasOne("printer.Data.Entities.Partner", "Partner")
                        .WithMany("Contacts")
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("printer.Data.Entities.PartnerModule", b =>
                {
                    b.HasOne("printer.Data.Entities.SystemModule", "Module")
                        .WithMany()
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("printer.Data.Entities.Partner", "Partner")
                        .WithMany()
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("printer.Data.Entities.PrintRecord", b =>
                {
                    b.HasOne("printer.Data.Entities.Partner", "Partner")
                        .WithMany()
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("printer.Data.Entities.Printer", "Printer")
                        .WithMany("PrintRecords")
                        .HasForeignKey("PrinterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partner");

                    b.Navigation("Printer");
                });

            modelBuilder.Entity("printer.Data.Entities.Printer", b =>
                {
                    b.HasOne("printer.Data.Entities.PrinterModel", "Model")
                        .WithMany("Printers")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("printer.Data.Entities.Partner", "Partner")
                        .WithMany("Printers")
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Model");

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("printer.Data.Entities.PrinterBillingConfig", b =>
                {
                    b.HasOne("printer.Data.Entities.Printer", "Printer")
                        .WithOne()
                        .HasForeignKey("printer.Data.Entities.PrinterBillingConfig", "PrinterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Printer");
                });

            modelBuilder.Entity("printer.Data.Entities.PrinterMaintainer", b =>
                {
                    b.HasOne("printer.Data.Entities.Printer", "Printer")
                        .WithMany("Maintainers")
                        .HasForeignKey("PrinterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("printer.Data.Entities.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Printer");

                    b.Navigation("User");
                });

            modelBuilder.Entity("printer.Data.Entities.PrinterModel", b =>
                {
                    b.HasOne("printer.Data.Entities.Brand", "Brand")
                        .WithMany("Models")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("printer.Data.Entities.BillingTemplate", b =>
                {
                    b.Navigation("Tiers");
                });

            modelBuilder.Entity("printer.Data.Entities.Brand", b =>
                {
                    b.Navigation("Models");
                });

            modelBuilder.Entity("printer.Data.Entities.Invoice", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("printer.Data.Entities.Partner", b =>
                {
                    b.Navigation("BillingInfos");

                    b.Navigation("Contacts");

                    b.Navigation("Printers");
                });

            modelBuilder.Entity("printer.Data.Entities.Printer", b =>
                {
                    b.Navigation("AlertRecords");

                    b.Navigation("Maintainers");

                    b.Navigation("PrintRecords");
                });

            modelBuilder.Entity("printer.Data.Entities.PrinterBillingConfig", b =>
                {
                    b.Navigation("Tiers");
                });

            modelBuilder.Entity("printer.Data.Entities.PrinterModel", b =>
                {
                    b.Navigation("Printers");
                });
#pragma warning restore 612, 618
        }
    }
}
